### PR TITLE
Move root of packages directory structure exact inside configured output path

### LINKED ISSUE #20: output and packageName configuration not working
maven plugin configuration:

<output>${project.basedir}/src/main/java</output>
<packageName>com.mycomp.prod.parser</packageName>

the plugin always create an extra directory "src"  in the front.  The above will put the generated java file in ${project.basedir}/src/main/java/src/com/mycomp/prod/parser/ directory

### PR DESCRIPTION
**Pull request by valery1707**
Fixes #20

### CODE REVIEW

**Comment by valery1707** [comment]
@RaymondHsu what you think about this property?

File: src/test/java/name/valery1707/kaitai/KaitaiUtilsTest.java [hunk 1]
```diff
@@ -112,9 +93,279 @@ public void testScanFiles() throws KaitaiException {
...
+		testDelete_fileLocked(fs);
+	}
+
+	private Path createPathTree(Path root, Map<String[], Character> content) throws IOException {
+		for (String[] paths : content.keySet()) {
+			Path path = root;
+			for (String part : paths) {
+				path = path.resolve(part);
+			}
+			switch (content.get(paths)) {
```
Comment (sputnikci) [inline src/test/java/name/valery1707/kaitai/KaitaiUtilsTest.java]: \[FindBugs\] INFO: SF: Switch statement found in name\.valery1707\.kaitai\.KaitaiUtilsTest\.createPathTree\(Path, Map\) where default case is missing

Comment (sputnikci) [inline src/test/java/name/valery1707/kaitai/KaitaiUtilsTest.java]: \[FindBugs\] INFO: WMI: name\.valery1707\.kaitai\.KaitaiUtilsTest\.createPathTree\(Path, Map\) makes inefficient use of keySet iterator instead of entrySet iterator

**Comment by bjohnso5** [comment]
Is it possible to get this merged and published for use? I have the same issue that @RaymondHsu is running into and this seems like a good fix

**Comment by valery1707** [comment]
@bjohnso5 yes of course. I will release new version soon.

**Comment by valery1707** [comment]
@rultor merge

**Comment by valery1707** [comment]
@rultor deploy, tag=0.1.5, next=0.1.6

**Comment by valery1707** [comment]
@bjohnso5 version `0.1.5` was released and will be accessible soon on maven central

**Comment by valery1707** [comment]
@bjohnso5 version `0.1.5` already [accessible](https://search.maven.org/search?q=a:kaitai-maven-plugin&core=gav) on maven.
